### ISSUE TITLE
Install command in readme doesn't seem to work

### ISSUE THREAD

**Issue by daveansell** [SolidCode/SolidPython#53]
in the readme the install command is:
sudo python setup.py --install
I found I had to use:
sudo python setup.py install

thanks
   Dave

**Comment by arpit1997** [comment]
@daveansell 
Thank you for reporting the bug. I guess this might just be a typo. because this is a very old version thing.
and perhaps ..
Glad to hear that you figured it by yourself.But you might consider changing the tile from command not work to `typo in the command`. It might be much helpful becuase this is no bug just a silly mistake,
Hope this is reasonable.
Thank you :smiley_cat: :smiley_cat:

**Comment by etjones** [comment]
Fixed in 4849d9b25b768a39bf5d6007b9d76f979d8c4178.  Will be pushed to PyPI shortly
